# Generated by Django 3.2.6 on 2023-04-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=50)),
                ('mon_type', models.IntegerField(blank=True, choices=[(1, 'Web Page - String'), (2, 'Ping'), (3, 'Port Open'), (5, 'SSL Valid'), (6, 'Network Latency'), (7, 'Packet Loss')], default=1, null=True)),
                ('check_operator', models.IntegerField(blank=True, choices=[(1, 'Positive Integer'), (2, 'Negative Integer')], default=1, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('host', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('port', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('ignore_ssl_verification', models.BooleanField(default=False)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('json_response', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Down'), (2, 'Warn'), (3, 'UP')], default=1, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_raw', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmonitor.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmonitor.monitor')),
            ],
        ),
    ]
