# Generated by Django 3.2.6 on 2023-04-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='string_check',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
