# Generated by Django 3.2.6 on 2023-04-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0002_monitor_string_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mon_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Web Page'), (2, 'Ping'), (3, 'Port Open'), (5, 'SSL Valid'), (6, 'Network Latency'), (7, 'Packet Loss')], default=1, null=True),
        ),
    ]
