# Generated by Django 3.2.18 on 2023-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0004_auto_20230430_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='use_auth2_token',
            field=models.BooleanField(default=False),
        ),
    ]
