# Generated by Django 3.2.18 on 2023-07-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0010_auto_20230718_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='use_basic_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
