# Generated by Django 3.2.18 on 2023-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0011_auto_20230728_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
