# Generated by Django 3.2.18 on 2023-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0013_auto_20230728_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='down',
            new_name='down_value',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='up',
            new_name='up_value',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='warn',
            new_name='warn_value',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mon_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Web Page'), (2, 'Ping'), (3, 'Port Open'), (5, 'SSL Valid'), (6, 'Network Latency'), (7, 'Packet Loss'), (8, 'URL (JSON Key)')], default=1, null=True),
        ),
    ]
