# Generated by Django 3.2.19 on 2023-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0018_newticketfilternotification_last_update_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newticketfilternotification',
            name='last_update_str',
        ),
        migrations.AddField(
            model_name='ticketfilter',
            name='last_update_str',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
