# Generated by Django 3.2.19 on 2023-09-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0019_auto_20230907_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketfilter',
            name='last_update_str',
        ),
        migrations.AddField(
            model_name='tickets',
            name='last_update_str',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
