# Generated by Django 3.2.19 on 2024-01-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0020_auto_20230907_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='status_code',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mon_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Web Page'), (2, 'Ping'), (3, 'Port Open'), (5, 'SSL Valid'), (6, 'Network Latency'), (7, 'Packet Loss'), (8, 'URL (JSON Key)'), (9, 'HTTP Status Code')], default=1, null=True),
        ),
    ]
