# Generated by Django 3.2.19 on 2024-01-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0022_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmonitor.platform')),
            ],
        ),
        migrations.CreateModel(
            name='PythonPackageVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_version', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('python_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmonitor.pythonpackage')),
            ],
        ),
    ]
