# Generated by Django 3.2.19 on 2024-01-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0023_pythonpackage_pythonpackageversionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
