# Generated by Django 3.2.19 on 2024-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0024_pythonpackage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackage',
            name='current_package_version',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
