# Generated by Django 3.2.19 on 2024-01-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0025_pythonpackage_current_package_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackage',
            name='json_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
