# Generated by Django 3.2.19 on 2024-01-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0026_pythonpackage_json_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonpackage',
            name='json_response',
        ),
        migrations.AddField(
            model_name='platform',
            name='json_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
