# Generated by Django 3.2.19 on 2024-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0028_platform_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackage',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
