# Generated by Django 3.2.19 on 2024-01-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0029_pythonpackage_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='stale_packages',
            field=models.BooleanField(default=True),
        ),
    ]
