# Generated by Django 3.2.23 on 2024-01-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0037_platform_last_sync_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='last_sync_date',
            new_name='last_sync_dt',
        ),
    ]
