# Generated by Django 3.2.23 on 2024-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0038_rename_last_sync_date_platform_last_sync_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.IntegerField(blank=True, choices=[(1, 'View Access'), (2, 'Create and Edit Access')], default=None, null=True)),
                ('group_name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
