# Generated by Django 3.2.23 on 2024-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0040_platform_vulnerability_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgroup',
            name='access_type',
            field=models.IntegerField(blank=True, choices=[(1, 'View Monitoring Status'), (2, 'Create and Edit Access Platforms'), (3, 'View Access Platform Status'), (4, 'View Access Package Status')], default=None, null=True),
        ),
    ]
