# Generated by Django 3.2.23 on 2024-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0042_alter_accessgroup_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='sharepoint_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='sharepoint_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='sharepoint_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mon_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Web Page'), (2, 'Ping'), (3, 'Port Open'), (5, 'SSL Valid'), (6, 'Network Latency'), (7, 'Packet Loss'), (8, 'URL (JSON Key)'), (9, 'HTTP Status Code'), (10, 'SharePoint Auth Check')], default=1, null=True),
        ),
    ]
