# Generated by Django 3.2.23 on 2024-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0043_auto_20240112_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='db_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='db_password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='db_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='db_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Postgres')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='db_username',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mon_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Web Page'), (2, 'Ping'), (3, 'Port Open'), (5, 'SSL Valid'), (6, 'Network Latency'), (7, 'Packet Loss'), (8, 'URL (JSON Key)'), (9, 'HTTP Status Code'), (10, 'SharePoint Auth Check'), (11, 'DB Timing'), (12, 'DB Query')], default=1, null=True),
        ),
    ]
