# Generated by Django 3.2.23 on 2024-01-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0044_auto_20240115_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='db_port',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
