# Generated by Django 3.2.23 on 2024-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0045_monitor_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='db_host',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
