# Generated by Django 3.2.23 on 2024-02-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0046_monitor_db_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='host',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
