# Generated by Django 3.2.24 on 2024-06-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0048_monitoralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='no_html_email',
            field=models.BooleanField(default=False),
        ),
    ]
