# Generated by Django 5.0.7 on 2024-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0049_monitoralert_no_html_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='response_type',
            field=models.IntegerField(blank=True, choices=[(1, 'On Call'), (2, 'Business Hours')], default=1, null=True),
        ),
    ]
