# Generated by Django 5.0.8 on 2024-10-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0050_monitor_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
    ]
