# Generated by Django 5.0.9 on 2024-11-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0051_monitor_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonpackage',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
