# Generated by Django 5.0.8 on 2024-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0053_alter_pythonpackage_vulnerability_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='git_repo_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
