# Generated by Django 5.0.9 on 2024-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0055_pythondependabotadvisory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythondependabotadvisory',
            name='ghsa_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
