# Generated by Django 5.0.9 on 2024-11-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0056_pythondependabotadvisory_ghsa_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonDependaBotAdvisory',
            new_name='PlatformDependaBotAdvisory',
        ),
    ]
