# Generated by Django 5.0.9 on 2024-11-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0059_platform_dependabot_vulnerability_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebianPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('current_package_version', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vulnerability_total', models.IntegerField(default=0, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmonitor.platform')),
            ],
        ),
    ]
