# Generated by Django 5.2.1 on 2025-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0062_monitor_help_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackage',
            name='severity_rollup',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
