# Generated by Django 5.2.1 on 2025-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0063_pythonpackage_severity_rollup'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_current_severity',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
