# Generated by Django 5.2.2 on 2025-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0065_ticketstatus_ticketsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketsystem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
