# Generated by Django 5.2.1 on 2025-08-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0067_debianpackagevulnerability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debianpackage',
            name='severity_rollup',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
