# Generated by Django 5.2.1 on 2025-09-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0071_npmpackagevulnerability_npmpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npmpackage',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
