# Generated by Django 5.2.9 on 2026-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0073_alter_npmpackagevulnerabilityversion_npm_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfilter',
            name='email_group',
            field=models.IntegerField(blank=True, choices=[(0, 'Full list'), (1, 'Group List')], default=0, null=True),
        ),
    ]
