# Generated by Django 5.2.14 on 2026-05-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0074_ticketfilter_email_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevopsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('devopsurl', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('wiql_query', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevopsReportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('devopsreport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmonitor.devopsreport')),
            ],
        ),
    ]
