# Generated by Django 5.2.14 on 2026-05-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0075_devopsreport_devopsreportnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='devopsreport',
            name='sort_order',
            field=models.IntegerField(blank=True, choices=[(0, 'Devops Query Order'), (1, 'Priorty Status')], default=0, null=True),
        ),
    ]
