# Generated by Django 5.2.15 on 2026-06-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonitor', '0076_devopsreport_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='image_tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
